### ISSUE TITLE
Using repository build crashes on startup

### ISSUE THREAD

**Issue by javierdlr** [salass00/srec#4]
Hi, downloading from repository src, building (GCC 4.2.4) without rpobelsm, but when laucnhing I get a crash/GR:

Crash log for task "SRec"
Generated by GrimReaper 53.19
Crash occured in module SRec at address 0x7F9C0EE0
Type of crash: DSI (Data Storage Interrupt) exception
Alert number: 0x80000003

Register dump:
GPR (General Purpose Registers):
   0: 00000063 571CB710 00000000 00000000 58066A3A 57D3BC19 00000007 00000000 
   8: 60A8227C 00000000 00000053 00000028 48822244 5A6EA358 00000000 5A222C82 
  16: 8000000C 80000001 5A6E0000 00000000 00000000 00000000 00000000 00000000 
  24: 00000000 00000000 5A6E0000 580660D0 571CB71C 7FFC3DC8 60AC22F0 571DA770 

FPR (Floating Point Registers, NaN = Not a Number):
   0:              nan              2.2          0.45455     7.48725e-196 
   4:    -2.64782e+263     1.32831e+181           667000               64 
   8:               64                1               64               64 
  12:               64       4.5036e+15         -35.5777    -1.14061e+295 
  16:     4.99375e+279     -3.77122e-05     1.15632e+140     -4.73803e-87 
  20:     1.76559e+299     1.72346e+217    -3.61707e+229     -3.82855e-96 
  24:    -7.64416e+282     3.30727e+253    -4.36226e+224    -1.79242e+217 
  28:     1.48715e-126     5.46713e+300    -8.07562e+221    -6.87755e+144 

FPSCR (Floating Point Status and Control Register): 0x82000000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002F030
                Condition (cr) : 0x5723DBF4
      Instruction Pointer (ip) : 0x7F9C0EE0
       Xtended Exception (xer) : 0x57FFF028
                   Count (ctr) : 0x6FF8E4D0
                     Link (lr) : 0x7FC4F5E0
            DSI Status (dsisr) : 0x57FFEDE0
            Data Address (dar) : 0x01AD4E88

680x0 emulated registers:
DATA: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x7F9C0EE0 belongs to module "SRec" (PowerPC) 
Symbol: gui_register_broker + 0x1C4 in section 1 offset 0x00001EDC

Stack trace:
    SRec:gui_register_broker()+0x1c4 (section 1 @ 0x1EDC)
    SRec:gui_register_broker()+0x1a4 (section 1 @ 0x1EBC)
    SRec:main()+0x17c (section 1 @ 0x360)
    native kernel module newlib.library.kmod+0x00001e94
    native kernel module newlib.library.kmod+0x00003014
    native kernel module newlib.library.kmod+0x000030c0
    SRec:_start()+0x170 (section 1 @ 0x16C)
    native kernel module dos.library.kmod+0x00026180
    native kernel module kernel.debug+0x00067db0
    native kernel module kernel.debug+0x00067df8

PPC disassembly:
 7f9c0ed8: 909f008c   stw               r4,140(r31)
 7f9c0edc: 813f0090   lwz               r9,144(r31)
*7f9c0ee0: 88090000   lbz               r0,0(r9)
 7f9c0ee4: 2f800000   cmpwi             cr7,r0,0
 7f9c0ee8: 409e0008   bne-              cr7,0x7F9C0EF0

System information:

CPU 
 Model: AMCC PPC460EX V1.2 
 CPU speed: 1155 MHz 
 FSB speed: 231 MHz 
 Extensions:  
[Crashlog_SRec.txt](https://github.com/salass00/srec/files/524024/Crashlog_SRec.txt)

**Comment by javierdlr** [comment]
and maybe changing 'CFLAGS  := -O2 -g' to use '-gstabs' can help tracking down on .debug executables

**Comment by salass00** [comment]
Already fixed:
https://github.com/salass00/srec/commit/abea5860a919c872471bcc5569bf9b680c2723fa
