### ISSUE TITLE
GUI string_gd MSG_KEY_NONE uses '_' shows underlined

### ISSUE THREAD

**Issue by javierdlr** [salass00/srec#5]
MSG_KEY_NONE
sin_asignar
; none

As I use '_' in such string in hotkey stringgadget shows it underlined, can be "fixed" by setting 
GA_Underscore,0
tag

**Comment by javierdlr** [comment]
BTW I see in .CD there is MSG_AUDIO_CODEC_PCM, so is it a Work In Progress feature? Is it usable with/on latest nightly builds?

Just courosity ;-)

**Comment by salass00** [comment]
Fixed.

Regarding MSG_AUDIO_CODEC_PCM it is just a place holder for now and was added just before 2.1 release:

https://github.com/salass00/srec/commit/67bd56b052fe1d8191b3ee4511fa61f07d9ece68
